version: '2'
services:
    jhipster_sandbox-app:
        image: jhipster_sandbox
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster_sandbox-mysql:3306/jhipster_sandbox?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_sandbox-mysql:
        extends:
            file: mysql.yml
            service: jhipster_sandbox-mysql
